language: node_js
node_js:
-12.16.3
cache: npm 


install:
  -npm ci
script:
  -npm test
  -npm run build 
deploy:
  provider: pages 
  skin-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages